<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5dfcbc32eb2b2',
	'title' => 'MastHead',
	'fields' => array(
		array(
			'key' => 'field_5dfcbc32f1066',
			'label' => 'Masthead Slider',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'placement' => 'top',
			'endpoint' => 0,
			'acfe_form' => true,
		),
		array(
			'key' => 'field_5e37e9df75619',
			'label' => 'Masthead style',
			'name' => 'hmhs_sty',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'choices' => array(
				'full_slider' => 'Image Slider or Youtube video',
				'no_image_top' => 'No Image BG',
				'clean_top' => 'Clean Image Short Head',
				'manual_slider' => 'Full Manual slider',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'save_other_choice' => 0,
			'acfe_form' => true,
		),
		array(
			'key' => 'field_5ea54fbd23940',
			'label' => 'Slider Height',
			'name' => 'hmh_he',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5e37e9df75619',
						'operator' => '==',
						'value' => 'manual_slider',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => 100,
			'placeholder' => '',
			'prepend' => '',
			'append' => '%',
			'min' => 20,
			'max' => 100,
			'step' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'acfe_form' => true,
		),
		array(
			'key' => 'field_5ea5501723941',
			'label' => 'Show Content under image on Mobile',
			'name' => 'hmh_mocon',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5e37e9df75619',
						'operator' => '==',
						'value' => 'manual_slider',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
			'ui_on_text' => '',
			'ui_off_text' => '',
			'acfe_form' => true,
		),
		array(
			'key' => 'field_5dfcbc32f10a1',
			'label' => 'Slider',
			'name' => 'hmhs_slider',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5e37e9df75619',
						'operator' => '==',
						'value' => 'manual_slider',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'acfe_repeater_stylised_button' => 0,
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => '',
			'acfe_settings' => '',
			'acfe_form' => true,
			'sub_fields' => array(
				array(
					'key' => 'field_5e8b81c1441c2',
					'label' => 'Show BG Overlay',
					'name' => 'hmhs_bgo',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'message' => '',
					'default_value' => 0,
					'ui' => 0,
					'acfe_settings' => '',
					'acfe_validate' => '',
					'ui_on_text' => '',
					'ui_off_text' => '',
					'acfe_form' => true,
				),
				array(
					'key' => 'field_5e8b90d1f9ef7',
					'label' => 'Content side',
					'name' => 'hmhs_scon',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'choices' => array(
						'start' => 'start',
						'center' => 'center',
						'end' => 'end',
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'acfe_settings' => '',
					'acfe_validate' => '',
					'ajax' => 0,
					'placeholder' => '',
					'acfe_form' => true,
				),
				array(
					'key' => 'field_5dfcbc330fa93',
					'label' => 'BackGround',
					'name' => 'hmhs_sico',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'acfe_uploader' => 'wp',
					'acfe_thumbnail' => 0,
					'return_format' => 'id',
					'preview_size' => 'menu-50',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'acfe_settings' => '',
					'acfe_validate' => '',
					'acfe_form' => true,
				),
				array(
					'key' => 'field_5dfcbc330fad3',
					'label' => 'Title',
					'name' => 'hmhs_sti',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'acfe_settings' => '',
					'acfe_validate' => '',
					'acfe_form' => true,
				),
				array(
					'key' => 'field_5e024bd20d498',
					'label' => 'Title Type',
					'name' => 'hmhs_stit',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'choices' => array(
						'h1' => 'h1',
						'h2' => 'h2',
						'div' => 'div',
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'acfe_settings' => '',
					'acfe_validate' => '',
					'ajax' => 0,
					'placeholder' => '',
					'acfe_form' => true,
				),
				array(
					'key' => 'field_5e8b83cf2cca1',
					'label' => 'Font size',
					'name' => 'hmhs_stis',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => 50,
					'placeholder' => '',
					'prepend' => '',
					'append' => 'px',
					'min' => 10,
					'max' => 300,
					'step' => 1,
					'acfe_settings' => '',
					'acfe_validate' => '',
					'acfe_form' => true,
				),
				array(
					'key' => 'field_5e8b84092cca2',
					'label' => 'Font color',
					'name' => 'hmhs_stic',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'acfe_settings' => '',
					'acfe_validate' => '',
					'acfe_form' => true,
				),
				array(
					'key' => 'field_5dfcbc330fb11',
					'label' => 'Subtitle',
					'name' => 'hmhs_ssti',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 4,
					'new_lines' => 'br',
					'acfe_textarea_code' => 0,
					'acfe_settings' => '',
					'acfe_validate' => '',
					'acfe_form' => true,
				),
				array(
					'key' => 'field_5e8b912cf9ef8',
					'label' => 'Subtitle Font size',
					'name' => 'hmhs_sstis',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => 25,
					'placeholder' => '',
					'prepend' => '',
					'append' => 'px',
					'min' => 10,
					'max' => 300,
					'step' => 1,
					'acfe_settings' => '',
					'acfe_validate' => '',
					'acfe_form' => true,
				),
				array(
					'key' => 'field_5e8b9141f9ef9',
					'label' => 'Subtitle Font color',
					'name' => 'hmhs_sstic',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'acfe_settings' => '',
					'acfe_validate' => '',
					'acfe_form' => true,
				),
				array(
					'key' => 'field_5e8b9168f9efa',
					'label' => 'Pre text',
					'name' => 'hmhs_spre',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'acfe_settings' => '',
					'acfe_validate' => '',
					'acfe_form' => true,
				),
				array(
					'key' => 'field_5e8b919df9efb',
					'label' => 'Pre Font size',
					'name' => 'hmhs_spres',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => 20,
					'placeholder' => '',
					'prepend' => '',
					'append' => 'px',
					'min' => 10,
					'max' => 300,
					'step' => 1,
					'acfe_settings' => '',
					'acfe_validate' => '',
					'acfe_form' => true,
				),
				array(
					'key' => 'field_5e8b91cff9efc',
					'label' => 'Pre Font color',
					'name' => 'hmhs_sprec',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'acfe_settings' => '',
					'acfe_validate' => '',
					'acfe_form' => true,
				),
				array(
					'key' => 'field_5dfcbc32f0f16',
					'label' => 'Button text',
					'name' => 'hmh_btn',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'acfe_settings' => '',
					'acfe_validate' => '',
					'acfe_form' => true,
				),
				array(
					'key' => 'field_5e8b9225f9efd',
					'label' => 'Button Color',
					'name' => 'hmhs_btnc',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'acfe_settings' => '',
					'acfe_validate' => '',
					'acfe_form' => true,
				),
				array(
					'key' => 'field_5e8b9241f9efe',
					'label' => 'Font Button Color',
					'name' => 'hmhs_btnf',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'acfe_settings' => '',
					'acfe_validate' => '',
					'acfe_form' => true,
				),
				array(
					'key' => 'field_5dfcbc32f0f50',
					'label' => 'Button type',
					'name' => 'hmh_btnty',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'choices' => array(
						'page' => 'link to page',
						'form' => 'Form popup',
						'link' => 'Free link',
						'link_new' => 'Free link to new tab',
						'video' => 'Youtube video popup',
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'acfe_settings' => '',
					'acfe_validate' => '',
					'ajax' => 0,
					'placeholder' => '',
					'acfe_form' => true,
				),
				array(
					'key' => 'field_5dfcbc32f0f8a',
					'label' => 'Yotube link url',
					'name' => 'hmh_vid',
					'type' => 'oembed',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5dfcbc32f0f50',
								'operator' => '==',
								'value' => 'video',
							),
						),
					),
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'width' => 300,
					'height' => 200,
					'acfe_settings' => '',
					'acfe_validate' => '',
					'acfe_form' => true,
				),
				array(
					'key' => 'field_5dfcbc32f0fc5',
					'label' => 'Form',
					'name' => 'hmh_form',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5dfcbc32f0f50',
								'operator' => '==',
								'value' => 'form',
							),
						),
					),
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'post_type' => array(
						0 => 'wpcf7_contact_form',
					),
					'taxonomy' => '',
					'allow_null' => 0,
					'multiple' => 0,
					'return_format' => 'id',
					'allow_custom' => 0,
					'save_post_status' => 'publish',
					'acfe_bidirectional' => array(
						'acfe_bidirectional_enabled' => '0',
					),
					'acfe_settings' => '',
					'acfe_validate' => '',
					'ui' => 1,
					'acfe_form' => true,
				),
				array(
					'key' => 'field_5dfcbc32f1000',
					'label' => 'Link page',
					'name' => 'hmh_page',
					'type' => 'page_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5dfcbc32f0f50',
								'operator' => '==',
								'value' => 'page',
							),
						),
					),
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'post_type' => array(
						0 => 'post',
						1 => 'page',
					),
					'taxonomy' => '',
					'allow_null' => 0,
					'allow_archives' => 1,
					'multiple' => 0,
					'acfe_settings' => '',
					'acfe_validate' => '',
					'acfe_form' => true,
				),
				array(
					'key' => 'field_5dfcbc32f103b',
					'label' => 'Free link',
					'name' => 'hmh_link',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5dfcbc32f0f50',
								'operator' => '==',
								'value' => 'link',
							),
						),
						array(
							array(
								'field' => 'field_5dfcbc32f0f50',
								'operator' => '==',
								'value' => 'link_new',
							),
						),
					),
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'acfe_settings' => '',
					'acfe_validate' => '',
					'acfe_form' => true,
				),
			),
		),
		array(
			'key' => 'field_5e4134612ce6f',
			'label' => 'Full Image Slider',
			'name' => 'mhfs',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5e37e9df75619',
						'operator' => '==',
						'value' => 'full_slider',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'acfe_settings' => '',
			'acfe_form' => true,
			'sub_fields' => array(
				array(
					'key' => 'field_5e4134ac2ce70',
					'label' => 'Slider Title',
					'name' => 'tit',
					'type' => 'text',
					'instructions' => 'H1 - Replace page name title',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'acfe_settings' => '',
					'acfe_validate' => '',
				),
				array(
					'key' => 'field_5e4134f12ce71',
					'label' => 'Page Sub Title',
					'name' => 'stit',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 4,
					'new_lines' => 'br',
					'acfe_textarea_code' => 0,
					'acfe_settings' => '',
					'acfe_validate' => '',
				),
				array(
					'key' => 'field_5ebd95c9e4248',
					'label' => 'Content align',
					'name' => 'cona',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '10',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'choices' => array(
						'right' => 'right',
						'center' => 'center',
						'left' => 'left',
					),
					'default_value' => false,
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'acfe_settings' => '',
					'acfe_validate' => '',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5e678decc266c',
					'label' => 'Slider Type',
					'name' => 'styp',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '10',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'choices' => array(
						'images' => 'images',
						'video' => 'video',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'default_value' => '',
					'layout' => 'vertical',
					'return_format' => 'value',
					'acfe_settings' => '',
					'acfe_validate' => '',
					'save_other_choice' => 0,
					'acfe_form' => true,
				),
				array(
					'key' => 'field_5e6b52c9747d0',
					'label' => 'Slider Height',
					'name' => 'shet',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '10',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => 100,
					'placeholder' => 'Height % of fold',
					'prepend' => '',
					'append' => '%',
					'min' => 10,
					'max' => 100,
					'step' => 1,
					'acfe_settings' => '',
					'acfe_validate' => '',
					'acfe_form' => true,
				),
				array(
					'key' => 'field_5e678b29c76b7',
					'label' => 'Show Image Ovelray',
					'name' => 'sover',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '10',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'message' => '',
					'default_value' => 0,
					'ui' => 0,
					'acfe_settings' => '',
					'acfe_validate' => '',
					'ui_on_text' => '',
					'ui_off_text' => '',
					'acfe_form' => true,
				),
				array(
					'key' => 'field_5e6e3094e266d',
					'label' => 'Image BG Fixed',
					'name' => 'ifix',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '10',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'message' => '',
					'default_value' => 0,
					'ui' => 0,
					'acfe_settings' => '',
					'acfe_validate' => '',
					'ui_on_text' => '',
					'ui_off_text' => '',
					'acfe_form' => true,
				),
				array(
					'key' => 'field_5e4135062ce72',
					'label' => 'Intro Text',
					'name' => 'txt',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
					'acfe_settings' => '',
					'acfe_validate' => '',
					'acfe_form' => true,
				),
				array(
					'key' => 'field_5e414232bfccb',
					'label' => 'Choose Images',
					'name' => 'gal',
					'type' => 'gallery',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e678decc266c',
								'operator' => '==',
								'value' => 'images',
							),
						),
					),
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'return_format' => 'array',
					'preview_size' => 'menu-50',
					'insert' => 'append',
					'library' => 'all',
					'min' => '',
					'max' => '',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'acfe_settings' => '',
					'acfe_validate' => '',
					'acfe_form' => true,
				),
				array(
					'key' => 'field_5e786ad503060',
					'label' => 'Icons list Images',
					'name' => 'sico',
					'type' => 'gallery',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e678decc266c',
								'operator' => '==',
								'value' => 'images',
							),
						),
					),
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'return_format' => 'id',
					'preview_size' => 'menu-50',
					'insert' => 'append',
					'library' => 'all',
					'min' => '',
					'max' => '',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'acfe_settings' => '',
					'acfe_validate' => '',
					'acfe_form' => true,
				),
				array(
					'key' => 'field_5ebd933c07626',
					'label' => 'Title color',
					'name' => 'titco',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'acfe_settings' => '',
					'acfe_validate' => '',
					'acfe_form' => true,
				),
				array(
					'key' => 'field_5ebd936907627',
					'label' => 'Subtitle color',
					'name' => 'stico',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'acfe_settings' => '',
					'acfe_validate' => '',
					'acfe_form' => true,
				),
				array(
					'key' => 'field_5ebd939d07628',
					'label' => 'Button color',
					'name' => 'btnco',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'acfe_settings' => '',
					'acfe_validate' => '',
					'acfe_form' => true,
				),
				array(
					'key' => 'field_5ebd93b207629',
					'label' => 'Title size',
					'name' => 'titsz',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => 'px',
					'min' => '',
					'max' => '',
					'step' => '',
					'acfe_settings' => '',
					'acfe_validate' => '',
					'acfe_form' => true,
				),
				array(
					'key' => 'field_5ebd93d40762a',
					'label' => 'Subtitle size',
					'name' => 'stsz',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => 'px',
					'min' => '',
					'max' => '',
					'step' => '',
					'acfe_settings' => '',
					'acfe_validate' => '',
					'acfe_form' => true,
				),
				array(
					'key' => 'field_5e678e31c266d',
					'label' => 'Youtube',
					'name' => 'vid',
					'type' => 'oembed',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e678decc266c',
								'operator' => '==',
								'value' => 'video',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'width' => '',
					'height' => '',
					'acfe_settings' => '',
					'acfe_validate' => '',
					'acfe_form' => true,
				),
				array(
					'key' => 'field_5e41356b2ce73',
					'label' => 'Slider Button',
					'name' => 'btn',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'acfe_settings' => '',
					'acfe_validate' => '',
					'acfe_form' => true,
				),
				array(
					'key' => 'field_5e4135812ce74',
					'label' => 'Button Link Type',
					'name' => 'btnlt',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'choices' => array(
						'page' => 'page',
						'link' => 'link',
						'form' => 'form',
						'video' => 'video',
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'acfe_settings' => '',
					'acfe_validate' => '',
					'ajax' => 0,
					'placeholder' => '',
					'acfe_form' => true,
				),
				array(
					'key' => 'field_5e41374e2ce75',
					'label' => 'Link to page',
					'name' => 'btnp',
					'type' => 'page_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e4135812ce74',
								'operator' => '==',
								'value' => 'page',
							),
						),
					),
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'post_type' => array(
						0 => 'page',
						1 => 'post',
					),
					'taxonomy' => '',
					'allow_null' => 0,
					'allow_archives' => 1,
					'multiple' => 0,
					'acfe_settings' => '',
					'acfe_validate' => '',
					'acfe_form' => true,
				),
				array(
					'key' => 'field_5ebd95a7e4247',
					'label' => 'Link',
					'name' => 'btnf',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e4135812ce74',
								'operator' => '==',
								'value' => 'link',
							),
						),
					),
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'acfe_settings' => '',
					'acfe_validate' => '',
				),
				array(
					'key' => 'field_5e41379d2ce78',
					'label' => 'Popup form',
					'name' => 'btnfo',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e4135812ce74',
								'operator' => '==',
								'value' => 'form',
							),
						),
					),
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'post_type' => array(
						0 => 'wpcf7_contact_form',
					),
					'taxonomy' => '',
					'allow_null' => 0,
					'multiple' => 0,
					'return_format' => 'id',
					'allow_custom' => 0,
					'save_post_status' => 'publish',
					'acfe_bidirectional' => array(
						'acfe_bidirectional_enabled' => '0',
					),
					'acfe_settings' => '',
					'acfe_validate' => '',
					'ui' => 1,
					'acfe_form' => true,
				),
				array(
					'key' => 'field_5e4137cc2ce79',
					'label' => 'Popup form title',
					'name' => 'btnfot',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e4135812ce74',
								'operator' => '==',
								'value' => 'form',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'acfe_settings' => '',
					'acfe_validate' => '',
					'acfe_form' => true,
				),
				array(
					'key' => 'field_5e4137da2ce7a',
					'label' => 'Popup form subtitle',
					'name' => 'btnfost',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e4135812ce74',
								'operator' => '==',
								'value' => 'form',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'acfe_settings' => '',
					'acfe_validate' => '',
					'acfe_form' => true,
				),
				array(
					'key' => 'field_5e4137ee2ce7c',
					'label' => 'Popup Youtube',
					'name' => 'btnv',
					'type' => 'oembed',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e4135812ce74',
								'operator' => '==',
								'value' => 'video',
							),
						),
					),
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'width' => '',
					'height' => '',
					'acfe_settings' => '',
					'acfe_validate' => '',
					'acfe_form' => true,
				),
			),
		),
		array(
			'key' => 'field_5e74ecdca3021',
			'label' => 'Clean Image Short Head',
			'name' => '',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5e37e9df75619',
						'operator' => '==',
						'value' => 'clean_top',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'open' => 1,
			'multi_expand' => 0,
			'endpoint' => 0,
			'acfe_form' => true,
		),
		array(
			'key' => 'field_5e74ec02a3020',
			'label' => 'Change BG image',
			'name' => 'mhsh_bgi',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'acfe_uploader' => 'wp',
			'acfe_thumbnail' => 0,
			'return_format' => 'id',
			'preview_size' => 'menu-100',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'acfe_form' => true,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'all',
			),
			array(
				'param' => 'post_type',
				'operator' => '!=',
				'value' => 'product',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_permissions' => '',
	'acfe_form' => 1,
	'acfe_meta' => '',
	'acfe_note' => '',
	'modified' => 1589483172,
));

endif;