<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5tk5cdb269e18ef7',
	'title' => 'MastHead',
	'fields' => array(
		array(
			'key' => 'field_5tk5c8e505e45130',
			'label' => 'Main Page Title',
			'name' => 'masthead_title',
			'type' => 'text',
			'instructions' => 'H1 - Replace page name title',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5tk5cdbb46c75871',
			'label' => 'Hide Main Page Title',
			'name' => 'masthead_title_hide',
			'type' => 'true_false',
			'instructions' => 'If main page title is hidden you should add an H1 title in page',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5tk5c8f46bfffa62',
			'label' => 'Second Featured Image',
			'name' => 'page_main_icon',
			'type' => 'image',
			'instructions' => 'Will be used as hover image effect',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5tk6t45a82e09623',
			'label' => 'MastHead on Mobile',
			'name' => 'masthead_on_mobile',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'same_desktop' => 'Same as Desktop',
				'mobile_masthead' => 'Different on Mobile',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5tk5c8e510sdw331',
			'label' => 'Page Sub Title',
			'name' => 'masthead_subtitle',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 4,
			'new_lines' => 'br',
		),
		array(
			'key' => 'field_5tk5c8e510c45131',
			'label' => 'Short Excerpt',
			'name' => 'masthead_excerpt',
			'type' => 'textarea',
			'instructions' => 'will be shown on related pages linked here',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 4,
			'new_lines' => 'br',
		),
		array(
			'key' => 'field_5tk5c8e515a45132',
			'label' => 'Intro Text',
			'name' => 'masthead_text',
			'type' => 'wysiwyg',
			'instructions' => 'Position will be set by slider masthead style',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'full_slider',
					),
				),
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'no_image_top',
					),
				),
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'clean_top',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array(
			'key' => 'field_5tk5c8e4d434512f',
			'label' => 'MastHead Top Slider',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5tk5c8f5f82d86b9',
			'label' => 'MastHead Style',
			'name' => 'page_top_slider_style',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '60',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'manual_split' => 'Manual Split slider',
				'no_image_top' => 'No Image BG',
				'full_slider' => 'Image Slider or Youtube video',
				'clean_top' => 'Clean Image Short Head',
				'manual_slider' => 'Full Manual slider',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5dma037ae401222',
			'label' => 'MastHead background color',
			'name' => 'masthead_background_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#ffffff',
		),
		array(
			'key' => 'field_5tk5c96a82e09651',
			'label' => 'Slider Effect',
			'name' => 'page_top_slider_effect',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'full_slider',
					),
				),
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'manual_slider',
					),
				),
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'clean_top',
					),
				),
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'manual_split',
					),
				),
			),
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'style1' => 'style1',
				'style2' => 'style2',
				'style3' => 'style3',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5tk5d2as119',
			'label' => 'Masthead BG Image',
			'name' => 'mh_split_bgimg',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'manual_split',
					),
				),
			),
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5tk5adsl2f9',
			'label' => 'Right BG Color',
			'name' => 'md_bg_r',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'manual_split',
					),
				),
			),
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array(
			'key' => 'field_5tk5vw62fd',
			'label' => 'Left BG Color',
			'name' => 'md_bg_l',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'manual_split',
					),
				),
			),
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array(
			'key' => 'field_5tk5c0k923e',
			'label' => 'Rotate Gradient bg',
			'name' => 'mh_bg_rotate',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'manual_split',
					),
				),
			),
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => 180,
			'placeholder' => '',
			'prepend' => '',
			'append' => 'deg',
			'min' => 0,
			'max' => 360,
			'step' => 1,
		),
		array(
			'key' => 'field_5tk5c978bcf63295',
			'label' => 'Main title color',
			'name' => 'masthead_title_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'no_image_top',
					),
				),
				array(
					array(
						'field' => 'field_5tk5c977a6af7f5e',
						'operator' => '==',
						'value' => 'slider_content_bottom',
					),
				),
			),
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array(
			'key' => 'field_5tk5c978b4663293',
			'label' => 'Intro text color',
			'name' => 'masthead_text_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'no_image_top',
					),
				),
				array(
					array(
						'field' => 'field_5tk5c977a6af7f5e',
						'operator' => '==',
						'value' => 'slider_content_bottom',
					),
				),
			),
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array(
			'key' => 'field_5tk5c97sd393',
			'label' => 'Intro background color',
			'name' => 'masthead_intro_bg_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'no_image_top',
					),
				),
				array(
					array(
						'field' => 'field_5tk5c977a6af7f5e',
						'operator' => '==',
						'value' => 'slider_content_bottom',
					),
				),
			),
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array(
			'key' => 'field_5tk5c977a6af7f5e',
			'label' => 'Title & Intro location',
			'name' => 'masthead_title_location',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'full_slider',
					),
				),
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'clean_top',
					),
				),
			),
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'slider_content_inn' => 'On top of the Image',
				'slider_content_bottom' => 'Under the image',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5tk5c9779d3f7f5c',
			'label' => 'Title & Intro Horizontal position',
			'name' => 'masthead_title_hor',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'full_slider',
					),
				),
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'clean_top',
					),
				),
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'no_image_top',
					),
				),
			),
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'start' => 'start',
				'center' => 'center',
				'end' => 'end',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5tk5c977a33f7f5d',
			'label' => 'Titile & Intro Vertical position',
			'name' => 'masthead_title_ver',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5tk5c977a6af7f5e',
						'operator' => '==',
						'value' => 'slider_content_inn',
					),
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'full_slider',
					),
				),
			),
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'top' => 'top',
				'middle' => 'middle',
				'bottom' => 'bottom',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5tk5c8e55e167281',
			'label' => 'MastHead Visual Height',
			'name' => 'page_top_slider_height',
			'type' => 'range',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'full_slider',
					),
				),
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'manual_slider',
					),
				),
			),
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => 100,
			'min' => 10,
			'max' => 100,
			'step' => '',
			'prepend' => '',
			'append' => '%',
		),
		array(
			'key' => 'field_5tk5c8e518c6b897',
			'label' => 'MastHead Type',
			'name' => 'page_top_slider_content',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'full_slider',
					),
				),
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'clean_top',
					),
				),
			),
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'image_slider' => 'Image / Image slider',
				'youtube_vid' => 'Youtube Video',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5dma03dbjbjfisdf',
			'label' => 'Hide slider overlay',
			'name' => 'page_top_slider_overlay',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'full_slider',
					),
				),
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'clean_top',
					),
				),
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'manual_slider',
					),
				),
				array(
					array(
						'field' => 'field_5tk5c977a6af7f5e',
						'operator' => '==',
						'value' => 'slider_content_inn',
					),
				),
			),
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5tk5c8e51916b898',
			'label' => 'Choose Images',
			'name' => 'page_main_top_slider',
			'type' => 'gallery',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5tk5c8e518c6b897',
						'operator' => '==',
						'value' => 'image_slider',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => '',
			'insert' => 'append',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'return_format' => 'array',
			'preview_size' => 'medium',
		),
		array(
			'key' => 'field_5tk5c8e51966b899',
			'label' => 'Youtube full URL',
			'name' => 'page_top_slider_youtube_vid',
			'type' => 'oembed',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5tk5c8e518c6b897',
						'operator' => '==',
						'value' => 'youtube_vid',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'width' => '',
			'height' => '',
		),
		array(
			'key' => 'field_5tk5csnnff651a',
			'label' => 'Button Type',
			'name' => 'masthead_btn_type',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'full_slider',
					),
				),
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'clean_top',
					),
				),
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'no_image_top',
					),
				),
			),
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'btn_text' => 'Text button',
				'btn_img' => 'Image button',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5tk5c99d0f44523',
			'label' => 'Button Style',
			'name' => 'masthead_button_style',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'full_slider',
					),
					array(
						'field' => 'field_5tk5csnnff651a',
						'operator' => '==',
						'value' => 'btn_text',
					),
				),
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'clean_top',
					),
					array(
						'field' => 'field_5tk5csnnff651a',
						'operator' => '==',
						'value' => 'btn_text',
					),
				),
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'no_image_top',
					),
					array(
						'field' => 'field_5tk5csnnff651a',
						'operator' => '==',
						'value' => 'btn_text',
					),
				),
			),
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'btn_style1' => 'Style 1',
				'btn_style2' => 'Style 2',
				'btn_style3' => 'Style 3',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5tk5c99dde13eea7',
			'label' => 'Button text color',
			'name' => 'masthead_btn_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'full_slider',
					),
					array(
						'field' => 'field_5tk5csnnff651a',
						'operator' => '==',
						'value' => 'btn_text',
					),
				),
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'clean_top',
					),
					array(
						'field' => 'field_5tk5csnnff651a',
						'operator' => '==',
						'value' => 'btn_text',
					),
				),
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'no_image_top',
					),
					array(
						'field' => 'field_5tk5csnnff651a',
						'operator' => '==',
						'value' => 'btn_text',
					),
				),
			),
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array(
			'key' => 'field_5tk5c99de133eea8',
			'label' => 'Button background color',
			'name' => 'masthead_btn_bg_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'full_slider',
					),
					array(
						'field' => 'field_5tk5csnnff651a',
						'operator' => '==',
						'value' => 'btn_text',
					),
				),
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'clean_top',
					),
					array(
						'field' => 'field_5tk5csnnff651a',
						'operator' => '==',
						'value' => 'btn_text',
					),
				),
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'no_image_top',
					),
					array(
						'field' => 'field_5tk5csnnff651a',
						'operator' => '==',
						'value' => 'btn_text',
					),
				),
			),
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array(
			'key' => 'field_5tk5c99d7e997b16',
			'label' => 'First Button - text',
			'name' => 'masthead_btn1_text',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'full_slider',
					),
					array(
						'field' => 'field_5tk5csnnff651a',
						'operator' => '==',
						'value' => 'btn_text',
					),
				),
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'clean_top',
					),
					array(
						'field' => 'field_5tk5csnnff651a',
						'operator' => '==',
						'value' => 'btn_text',
					),
				),
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'no_image_top',
					),
					array(
						'field' => 'field_5tk5csnnff651a',
						'operator' => '==',
						'value' => 'btn_text',
					),
				),
			),
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5tk5c99dssc46518',
			'label' => 'First Button - Image',
			'name' => 'masthead_btn1_img',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'full_slider',
					),
					array(
						'field' => 'field_5tk5csnnff651a',
						'operator' => '==',
						'value' => 'btn_img',
					),
				),
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'clean_top',
					),
					array(
						'field' => 'field_5tk5csnnff651a',
						'operator' => '==',
						'value' => 'btn_img',
					),
				),
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'no_image_top',
					),
					array(
						'field' => 'field_5tk5csnnff651a',
						'operator' => '==',
						'value' => 'btn_img',
					),
				),
			),
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'preview_size' => 'menu-50',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5tk5c99d83597b17',
			'label' => 'First Button - link',
			'name' => 'masthead_btn1_link',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'full_slider',
					),
				),
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'clean_top',
					),
				),
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'no_image_top',
					),
				),
			),
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5tk5c99d84d97b18',
			'label' => 'Second Button - text',
			'name' => 'masthead_btn2_text',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'full_slider',
					),
					array(
						'field' => 'field_5tk5csnnff651a',
						'operator' => '==',
						'value' => 'btn_text',
					),
				),
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'clean_top',
					),
					array(
						'field' => 'field_5tk5csnnff651a',
						'operator' => '==',
						'value' => 'btn_text',
					),
				),
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'no_image_top',
					),
					array(
						'field' => 'field_5tk5csnnff651a',
						'operator' => '==',
						'value' => 'btn_text',
					),
				),
			),
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5tk5c99dsnfgf6518',
			'label' => 'Second Button - Image',
			'name' => 'masthead_btn2_img',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'full_slider',
					),
					array(
						'field' => 'field_5tk5csnnff651a',
						'operator' => '==',
						'value' => 'btn_img',
					),
				),
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'clean_top',
					),
					array(
						'field' => 'field_5tk5csnnff651a',
						'operator' => '==',
						'value' => 'btn_img',
					),
				),
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'no_image_top',
					),
					array(
						'field' => 'field_5tk5csnnff651a',
						'operator' => '==',
						'value' => 'btn_img',
					),
				),
			),
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'preview_size' => 'menu-50',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5tk5c99d86397b19',
			'label' => 'Second Button - link',
			'name' => 'masthead_btn2_link',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'full_slider',
					),
				),
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'clean_top',
					),
				),
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'no_image_top',
					),
				),
			),
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5tk5cdfde3421a97',
			'label' => 'Manual Full Slider',
			'name' => 'page_top_slider_manual',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'manual_slider',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_5tk5cdfde5621a98',
					'label' => 'Background Type',
					'name' => 'slider_manual_bg',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '30',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'image_bg' => 'Image',
						'video_bg' => 'Video',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'default_value' => '',
					'layout' => 'vertical',
					'return_format' => 'value',
					'save_other_choice' => 0,
				),
				array(
					'key' => 'field_5tk5cdfde9921a99',
					'label' => 'Image',
					'name' => 'slider_manual_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5tk5cdfde5621a98',
								'operator' => '==',
								'value' => 'image_bg',
							),
						),
					),
					'wrapper' => array(
						'width' => '70',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'id',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_5tk5cdfdeb621a9a',
					'label' => 'Video URL',
					'name' => 'slider_manual_video',
					'type' => 'oembed',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5tk5cdfde5621a98',
								'operator' => '==',
								'value' => 'video_bg',
							),
						),
					),
					'wrapper' => array(
						'width' => '70',
						'class' => '',
						'id' => '',
					),
					'width' => '',
					'height' => '',
				),
				array(
					'key' => 'field_5tk5cdfded621a9b',
					'label' => 'Content on slide',
					'name' => 'slider_manual_content',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
				),
				array(
					'key' => 'field_5tk5cdsder4f123',
					'label' => 'Inner slide slider',
					'name' => 'inner_manual_slider',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 0,
					'max' => 0,
					'layout' => 'block',
					'button_label' => '',
					'sub_fields' => array(
						array(
							'key' => 'field_5tk5cddnfgt91',
							'label' => 'Image',
							'name' => 'inner_manual_slider_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'id',
							'preview_size' => 'menu-50',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array(
							'key' => 'field_5tk5c99sd4171',
							'label' => 'Title',
							'name' => 'inner_manual_slider_title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '20',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5tk5c8s3093221',
							'label' => 'Short Content',
							'name' => 'inner_manual_slider_text',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '35',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => 4,
							'new_lines' => 'br',
						),
						array(
							'key' => 'field_5tk5c99kd09je71',
							'label' => 'Link',
							'name' => 'inner_manual_slider_link',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '20',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
				),
				array(
					'key' => 'field_5tk5cdfdef421a9c',
					'label' => 'Contenet position on slide',
					'name' => 'slider_manual_content_position',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'center-xs middle-xs' => 'Center Middle',
						'center-xs top-xs' => 'Center Top',
						'center-xs bottom-xs' => 'Center Bottom',
						'top-xs start-xs' => 'Top Start',
						'middle-xs start-xs' => 'Middle Start',
						'bottom-xs start-xs' => 'Bottom Start',
						'top-xs end-xs' => 'Top End',
						'middle-xs end-xs' => 'Middle End',
						'bottom-xs end-xs' => 'Bottom End',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'default_value' => '',
					'layout' => 'horizontal',
					'return_format' => 'value',
					'save_other_choice' => 0,
				),
			),
		),
		array(
			'key' => 'field_5tk5cjf8a7',
			'label' => 'Manual Split Slider',
			'name' => 'mh_split',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'manual_split',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_5tk5d221a99',
					'label' => 'Side Image',
					'name' => 'mh_split_img',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'id',
					'preview_size' => 'menu-100',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_5tk5d20k9',
					'label' => 'Side Image - mobile',
					'name' => 'mh_split_img_m',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'id',
					'preview_size' => 'menu-100',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_5tk50dj66q1',
					'label' => 'Slide Title',
					'name' => 'mh_split_title',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 4,
					'new_lines' => 'br',
				),
				array(
					'key' => 'field_5tk5jjf7631',
					'label' => 'Slide SubTitle',
					'name' => 'mh_split_subtitle',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 4,
					'new_lines' => 'br',
				),
				array(
					'key' => 'field_5tk5csddk98',
					'label' => 'Title type',
					'name' => 'mh_split_title_type',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'h1' => 'H1',
						'h2' => 'H2',
						'h3' => 'H3',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'default_value' => '',
					'layout' => 'vertical',
					'return_format' => 'value',
					'save_other_choice' => 0,
				),
				array(
					'key' => 'field_5tk5jsk99q1',
					'label' => 'Slide Button text',
					'name' => 'mh_split_text',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 4,
					'new_lines' => 'br',
				),
				array(
					'key' => 'field_5tk5cs0fsh58',
					'label' => 'Link',
					'name' => 'mh_split_link_type',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'no_link' => 'No link',
						'video_popup' => 'Video popup',
						'link_page' => 'Link to page',
						'link_form' => 'Link to form',
						'link_new' => 'Link new',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'default_value' => '',
					'layout' => 'vertical',
					'return_format' => 'value',
					'save_other_choice' => 0,
				),
				array(
					'key' => 'field_5tk5chsiq1b5',
					'label' => 'Form link',
					'name' => 'mh_split_form',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5tk5cs0fsh58',
								'operator' => '==',
								'value' => 'link_form',
							),
						),
					),
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'wpcf7_contact_form',
					),
					'taxonomy' => '',
					'allow_null' => 0,
					'multiple' => 0,
					'return_format' => 'id',
					'ui' => 0,
				),
				array(
					'key' => 'field_5tk5cd72qa',
					'label' => 'Video URL',
					'name' => 'mh_split_vid',
					'type' => 'oembed',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5tk5cs0fsh58',
								'operator' => '==',
								'value' => 'video_popup',
							),
						),
					),
					'wrapper' => array(
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'width' => '',
					'height' => 100,
				),
				array(
					'key' => 'field_5tk5cs30jhf9',
					'label' => 'Slide btn link',
					'name' => 'mh_split_flink',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5tk5cs0fsh58',
								'operator' => '==',
								'value' => 'link_new',
							),
						),
					),
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5tk5d0lka42',
					'label' => 'Page link',
					'name' => 'mh_split_plink',
					'type' => 'page_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5tk5cs0fsh58',
								'operator' => '==',
								'value' => 'link_page',
							),
						),
					),
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'post_type' => '',
					'taxonomy' => '',
					'allow_null' => 0,
					'allow_archives' => 1,
					'multiple' => 0,
				),
			),
		),
		array(
			'key' => 'field_5tdsaw1b',
			'label' => 'Masthead main slogan',
			'name' => 'mh_split_slogan',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'manual_split',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array(
			'key' => 'field_5tkmobile5c8e4d434512f',
			'label' => 'Mobile MastHead Top Slider',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5tk6t45a82e09623',
						'operator' => '==',
						'value' => 'mobile_masthead',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5tkmobile5c8f5f82d86b9',
			'label' => 'MastHead Style',
			'name' => 'mobile_page_top_slider_style',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'full_slider' => 'Image Slider or Youtube video',
				'clean_top' => 'Clean Image Short Head',
				'no_image_top' => 'No Image BG',
				'manual_slider' => 'Full Manual slider',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5tkmobile5c96a82e09651',
			'label' => 'Slider Effect',
			'name' => 'mobile_page_top_slider_effect',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5tkmobile5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'full_slider',
					),
				),
				array(
					array(
						'field' => 'field_5tkmobile5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'manual_slider',
					),
				),
				array(
					array(
						'field' => 'field_5tkmobile5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'clean_top',
					),
				),
				array(
					array(
						'field' => 'field_5tkmobile5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'manual_split',
					),
				),
			),
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'style1' => 'style1',
				'style2' => 'style2',
				'style3' => 'style3',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5tkmobile5c978bcf63295',
			'label' => 'Main title color',
			'name' => 'mobile_masthead_title_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5tkmobile5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'no_image_top',
					),
				),
				array(
					array(
						'field' => 'field_5tkmobile5c977a6af7f5e',
						'operator' => '==',
						'value' => 'slider_content_bottom',
					),
				),
			),
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array(
			'key' => 'field_5tkmobile5c978b4663293',
			'label' => 'Intro text color',
			'name' => 'mobile_masthead_text_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5tkmobile5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'no_image_top',
					),
				),
				array(
					array(
						'field' => 'field_5tkmobile5c977a6af7f5e',
						'operator' => '==',
						'value' => 'slider_content_bottom',
					),
				),
			),
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array(
			'key' => 'field_5tk5c97sd3sse93',
			'label' => 'Intro background color',
			'name' => 'mobile_masthead_intro_bg_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5tkmobile5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'no_image_top',
					),
				),
				array(
					array(
						'field' => 'field_5tkmobile5c977a6af7f5e',
						'operator' => '==',
						'value' => 'slider_content_bottom',
					),
				),
			),
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array(
			'key' => 'field_5tkmobile5c977a6af7f5e',
			'label' => 'Title & Intro location',
			'name' => 'mobile_masthead_title_location',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'full_slider',
					),
				),
				array(
					array(
						'field' => 'field_5tk5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'clean_top',
					),
				),
			),
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'slider_content_inn' => 'On top of the Image',
				'slider_content_bottom' => 'Under the image',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5tkmobile5c9779d3f7f5c',
			'label' => 'Title & Intro Horizontal position',
			'name' => 'mobile_masthead_title_hor',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5tkmobile5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'full_slider',
					),
				),
				array(
					array(
						'field' => 'field_5tkmobile5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'clean_top',
					),
				),
			),
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'start' => 'start',
				'center' => 'center',
				'end' => 'end',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5tkmobile5c977a33f7f5d',
			'label' => 'Titile & Intro Vertical position',
			'name' => 'mobile_masthead_title_ver',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5tkmobile5c977a6af7f5e',
						'operator' => '==',
						'value' => 'slider_content_inn',
					),
					array(
						'field' => 'field_5tkmobile5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'full_slider',
					),
				),
			),
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'top' => 'top',
				'middle' => 'middle',
				'bottom' => 'bottom',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5tkmobile5c8e55e167281',
			'label' => 'MastHead Visual Height',
			'name' => 'mobile_page_top_slider_height',
			'type' => 'range',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5tkmobile5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'full_slider',
					),
				),
				array(
					array(
						'field' => 'field_5tkmobile5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'manual_slider',
					),
				),
			),
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => 100,
			'min' => 10,
			'max' => 100,
			'step' => '',
			'prepend' => '',
			'append' => '%',
		),
		array(
			'key' => 'field_5tkmobile5c8e518c6b897',
			'label' => 'MastHead Type',
			'name' => 'mobile_page_top_slider_content',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5tkmobile5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'full_slider',
					),
				),
				array(
					array(
						'field' => 'field_5tkmobile5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'clean_top',
					),
				),
			),
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'image_slider' => 'Image / Image slider',
				'youtube_vid' => 'Youtube Video',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5tkmobile5c8e51916b898',
			'label' => 'Choose Images',
			'name' => 'mobile_page_main_top_slider',
			'type' => 'gallery',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5tkmobile5c8e518c6b897',
						'operator' => '==',
						'value' => 'image_slider',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => '',
			'insert' => 'append',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'return_format' => 'array',
			'preview_size' => 'medium',
		),
		array(
			'key' => 'field_5tkmobile5c8e51966b899',
			'label' => 'Youtube full URL',
			'name' => 'mobile_page_top_slider_youtube_vid',
			'type' => 'oembed',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5tkmobile5c8e518c6b897',
						'operator' => '==',
						'value' => 'youtube_vid',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'width' => '',
			'height' => '',
		),
		array(
			'key' => 'field_5tkmobile5c99d7e997b16',
			'label' => 'First Button - text',
			'name' => 'mobile_masthead_btn1_text',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5tkmobile5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'full_slider',
					),
				),
				array(
					array(
						'field' => 'field_5tkmobile5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'clean_top',
					),
				),
				array(
					array(
						'field' => 'field_5tkmobile5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'no_image_top',
					),
				),
			),
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5tkmobile5c99d83597b17',
			'label' => 'First Button - link',
			'name' => 'mobile_masthead_btn1_link',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5tkmobile5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'full_slider',
					),
				),
				array(
					array(
						'field' => 'field_5tkmobile5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'clean_top',
					),
				),
				array(
					array(
						'field' => 'field_5tkmobile5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'no_image_top',
					),
				),
			),
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5tkmobile5c99d84d97b18',
			'label' => 'Second Button - text',
			'name' => 'mobile_masthead_btn2_text',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5tkmobile5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'full_slider',
					),
				),
				array(
					array(
						'field' => 'field_5tkmobile5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'clean_top',
					),
				),
				array(
					array(
						'field' => 'field_5tkmobile5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'no_image_top',
					),
				),
			),
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5tkmobile5c99d86397b19',
			'label' => 'Second Button - link',
			'name' => 'mobile_masthead_btn2_link',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5tkmobile5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'full_slider',
					),
				),
				array(
					array(
						'field' => 'field_5tkmobile5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'clean_top',
					),
				),
				array(
					array(
						'field' => 'field_5tkmobile5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'no_image_top',
					),
				),
			),
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5tkmobile5h6ts31a',
			'label' => 'Button Style',
			'name' => 'mobile_masthead_button_style',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5tkmobile5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'full_slider',
					),
				),
				array(
					array(
						'field' => 'field_5tkmobile5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'clean_top',
					),
				),
				array(
					array(
						'field' => 'field_5tkmobile5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'no_image_top',
					),
				),
			),
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'btn_style1' => 'Style 1',
				'btn_style2' => 'Style 2',
				'btn_style3' => 'Style 3',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5tkmobile5c99dde13eea7',
			'label' => 'Button text color',
			'name' => 'mobile_masthead_btn_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5tkmobile5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'full_slider',
					),
				),
				array(
					array(
						'field' => 'field_5tkmobile5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'clean_top',
					),
				),
				array(
					array(
						'field' => 'field_5tkmobile5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'no_image_top',
					),
				),
				array(
					array(
						'field' => 'field_5tkmobile5c977a6af7f5e',
						'operator' => '==',
						'value' => 'slider_content_bottom',
					),
				),
			),
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array(
			'key' => 'field_5tkmobile5c99de133eea8',
			'label' => 'Button background color',
			'name' => 'mobile_masthead_btn_bg_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5tkmobile5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'full_slider',
					),
				),
				array(
					array(
						'field' => 'field_5tkmobile5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'clean_top',
					),
				),
				array(
					array(
						'field' => 'field_5tkmobile5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'no_image_top',
					),
				),
				array(
					array(
						'field' => 'field_5tkmobile5c977a6af7f5e',
						'operator' => '==',
						'value' => 'slider_content_bottom',
					),
				),
			),
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array(
			'key' => 'field_5tkmobile5cdfde3421a97',
			'label' => 'Manual Full Slider',
			'name' => 'mobile_page_top_slider_manual',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5tkmobile5c8f5f82d86b9',
						'operator' => '==',
						'value' => 'manual_slider',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_5tkmobile5cdfde5621a98',
					'label' => 'Background Type',
					'name' => 'mobile_slider_manual_bg',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '30',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'image_bg' => 'Image',
						'video_bg' => 'Video',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'default_value' => '',
					'layout' => 'vertical',
					'return_format' => 'value',
					'save_other_choice' => 0,
				),
				array(
					'key' => 'field_5tkmobile5cdfde9921a99',
					'label' => 'Image',
					'name' => 'mobile_slider_manual_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5tkmobile5cdfde5621a98',
								'operator' => '==',
								'value' => 'image_bg',
							),
						),
					),
					'wrapper' => array(
						'width' => '70',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'id',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_5tkmobile5cdfdeb621a9a',
					'label' => 'Video URL',
					'name' => 'mobile_slider_manual_video',
					'type' => 'oembed',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5tkmobile5cdfde5621a98',
								'operator' => '==',
								'value' => 'video_bg',
							),
						),
					),
					'wrapper' => array(
						'width' => '70',
						'class' => '',
						'id' => '',
					),
					'width' => '',
					'height' => '',
				),
				array(
					'key' => 'field_5tkmobile5cdfded621a9b',
					'label' => 'Content on slide',
					'name' => 'mobile_slider_manual_content',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '70',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
				),
				array(
					'key' => 'field_5tkmobile5cdfdef421a9c',
					'label' => 'Contenet position on slide',
					'name' => 'mobile_slider_manual_content_position',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '30',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'center-xs middle-xs' => 'Center Middle',
						'top-xs middle-xs' => 'Top Middle',
						'bottom-xs middle-xs' => 'Bottom Middle',
						'top-xs start-xs' => 'Top Start',
						'middle-xs start-xs' => 'Middle Start',
						'bottom-xs start-xs' => 'Bottom Start',
						'top-xs end-xs' => 'Top End',
						'middle-xs end-xs' => 'Middle End',
						'bottom-xs end-xs' => 'Bottom End',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'default_value' => '',
					'layout' => 'vertical',
					'return_format' => 'value',
					'save_other_choice' => 0,
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 2,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'excerpt',
		1 => 'discussion',
		2 => 'comments',
	),
	'active' => 0,
	'description' => '',
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_permissions' => '',
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'modified' => 1576845241,
));

endif;